#########################################################
##              Projet configuration file              ##
#########################################################

# Executable name:
NAME = firmware

# Define: -D<symbol>
DEFINE =

# Project source files:
#SOURCE_PROJECT=usermain.c
SOURCE_PROJECT=main.c

# Include repertory : -I<repertory path>
HEADER_PROJECT=

# Path to project source code
SOURCE_PATH_PROJECT=./source

# Path to Klipos project directory:
KLIPOS_PATH=../../


mcu = lpc8xx

exception = no
kernel = no



#### compiler defines ####

# compiler optimization:
OPTIMIZE=-Os


#compiler options (CFLAGS):
COMPILER_OPTION	=$(OPTIMIZE)
COMPILER_OPTION += -Wall
COMPILER_OPTION += -Wextra
COMPILER_OPTION += -mthumb
COMPILER_OPTION += -mcpu=cortex-m0 -MD
COMPILER_OPTION += -ffunction-sections
COMPILER_OPTION	+= -fdata-sections
COMPILER_OPTION += -fno-builtin

# Activate debug for jtag :
# COMPILER_OPTION += -ggdb 

#linker options (LDFLAGS):
LINKER_OPTION = --gc-sections -T$(HW_LINKER_FILE)
LINKER_OPTION += -nostartfiles
LINKER_OPTION += -Wl,-Map=$(BUILD_PATH)/main.map,--cref,-nostdlib
LINKER_OPTION += -static
LINKER_OPTION += -mcpu=cortex-m0
LINKER_OPTION += -mthumb
LINKER_OPTION += -lc
LINKER_OPTION += -lgcc
LINKER_OPTION += -lm


