/*
 The MIT License (MIT)
 
 Copyright (c) 2015 Baptiste Burles
 
 Permission is hereby granted, free of charge, to any person obtaining a copy of
 this software and associated documentation files (the "Software"), to deal in
 the Software without restriction, including without limitation the rights to
 use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 the Software, and to permit persons to whom the Software is furnished to do so,
 subject to the following conditions:
 
 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
#ifndef LIB_HW_PINMUX_PINS_H
#define	LIB_HW_PINMUX_PINS_H

#ifdef	__cplusplus
extern "C" {
#endif

/* SCT input mux mapping selections for SCT0 inputs 0-6 */
typedef enum {
	SCT0_INMUX_PIO0_2 = 0,
	SCT0_INMUX_PIO0_3,
	SCT0_INMUX_PIO0_17,
	SCT0_INMUX_PIO0_30,
	SCT0_INMUX_PIO1_6,
	SCT0_INMUX_PIO1_7,
	SCT0_INMUX_PIO1_12,
	SCT0_INMUX_PIO1_13,
	SCT0_INMUX_SCT1_OUT4,
	SCT0_INMUX_SCT2_OUT4,
	SCT0_INMUX_SCT2_OUT5,
	SCT0_INMUX_ADC0_THCMP_IRQ,
	SCT0_INMUX_ADC1_THCMP_IRQ,
	SCT0_INMUX_ACMP0_OUT,
	SCT0_INMUX_ACMP1_OUT,
	SCT0_INMUX_ACMP2_OUT,
	SCT0_INMUX_ACMP3_OUT,
	SCT0_INMUX_SCTIPU_ABORT,
	SCT0_INMUX_SCTIPU_SAMPLE0,
	SCT0_INMUX_SCTIPU_SAMPLE1,
	SCT0_INMUX_SCTIPU_SAMPLE2,
	SCT0_INMUX_SCTIPU_SAMPLE3,
	SCT0_INMUX_DEBUG_HALTED
} SCT0_INMUX_T;


/* SCT input mux mapping selections for SCT1 inputs 0-6 */
typedef enum {
	SCT1_INMUX_PIO0_15 = 0,
	SCT1_INMUX_PIO0_16,
	SCT1_INMUX_PIO0_21,
	SCT1_INMUX_PIO0_31,
	SCT1_INMUX_PIO1_4,
	SCT1_INMUX_PIO1_5,
	SCT1_INMUX_PIO1_15,
	SCT1_INMUX_PIO1_16,
	SCT1_INMUX_SCT0_OUT4,
	SCT1_INMUX_SCT3_OUT4,
	SCT1_INMUX_SCT3_OUT5,
	SCT1_INMUX_ADC0_THCMP_IRQ,
	SCT1_INMUX_ADC1_THCMP_IRQ,
	SCT1_INMUX_ACMP0_OUT,
	SCT1_INMUX_ACMP1_OUT,
	SCT1_INMUX_ACMP2_OUT,
	SCT1_INMUX_ACMP3_OUT,
	SCT1_INMUX_SCTIPU_ABORT,
	SCT1_INMUX_SCTIPU_SAMPLE0,
	SCT1_INMUX_SCTIPU_SAMPLE1,
	SCT1_INMUX_SCTIPU_SAMPLE2,
	SCT1_INMUX_SCTIPU_SAMPLE3,
	SCT1_INMUX_DEBUG_HALTED
} SCT1_INMUX_T;


/* SCT input mux mapping selections for SCT2 inputs 0-2 */
typedef enum {
	SCT2_INMUX_PIO0_4 = 0,
	SCT2_INMUX_PIO0_27,
	SCT2_INMUX_PIO1_18,
	SCT2_INMUX_PIO1_19,
	SCT2_INMUX_SCT0_OUT4,
	SCT2_INMUX_SCT0_OUT5,
	SCT2_INMUX_SCT0_OUT7,
	SCT2_INMUX_SCT0_OUT8,
	SCT2_INMUX_ADC0_THCMP_IRQ,
	SCT2_INMUX_ADC1_THCMP_IRQ,
	SCT2_INMUX_ACMP0_OUT,
	SCT2_INMUX_ACMP1_OUT,
	SCT2_INMUX_ACMP2_OUT,
	SCT2_INMUX_ACMP3_OUT,
	SCT2_INMUX_SCTIPU_ABORT,
	SCT2_INMUX_SCTIPU_SAMPLE0,
	SCT2_INMUX_SCTIPU_SAMPLE1,
	SCT2_INMUX_SCTIPU_SAMPLE2,
	SCT2_INMUX_SCTIPU_SAMPLE3,
	SCT2_INMUX_USB_FRAME_TOGGLE,
	SCT2_INMUX_DEBUG_HALTED
} SCT2_INMUX_T;


/* SCT input mux mapping selections for SCT3 inputs 0-2 */
typedef enum {
	SCT3_INMUX_PIO0_7 = 0,
	SCT3_INMUX_PIO1_11,
	SCT3_INMUX_PIO1_21,
	SCT3_INMUX_PIO1_22,
	SCT3_INMUX_SCT1_OUT4,
	SCT3_INMUX_SCT1_OUT5,
	SCT3_INMUX_SCT1_OUT7,
	SCT3_INMUX_SCT1_OUT8,
	SCT3_INMUX_ADC0_THCMP_IRQ,
	SCT3_INMUX_ADC1_THCMP_IRQ,
	SCT3_INMUX_ACMP0_OUT,
	SCT3_INMUX_ACMP1_OUT,
	SCT3_INMUX_ACMP2_OUT,
	SCT3_INMUX_ACMP3_OUT,
	SCT3_INMUX_SCTIPU_ABORT3,
	SCT3_INMUX_SCTIPU_SAMPLE0,
	SCT3_INMUX_SCTIPU_SAMPLE1,
	SCT3_INMUX_SCTIPU_SAMPLE2,
	SCT3_INMUX_SCTIPU_SAMPLE3,
	SCT3_INMUX_USB_FRAME_TOGGLE,
	SCT3_INMUX_DEBUG_HALTED
} SCT3_INMUX_T;



#ifdef	__cplusplus
}
#endif

#endif	/* PINMUX_PINS_H */

